fail_fast: true
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:

  # =============================== Default Hooks ========================== {{{

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # git
      - id: no-commit-to-branch # enforce no direct commit to master also locally.
      - id: check-added-large-files # disallow large files, use lfs instead.
        args: ["--maxkb=1000"]

        # general
      - id: trailing-whitespace
      - id: check-executables-have-shebangs

        # python
      - id: requirements-txt-fixer
      - id: debug-statements # do not leave breakpoints in python

        # config files
      - id: check-json

      - id: pretty-format-json
        args: ["--autofix"]

      - id: check-yaml
      - id: check-toml
      - id: check-xml

  # }}}

  # ================================== C/C++ =============================== {{{

  # linting
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    - id: clang-format
    - id: clang-tidy

  # }}}

  # ============================== commit messages ========================= {{{

  # enforce conventional commits
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [push]

  # }}}